#!/usr/bin/env python3
"""Generate supplemental monorepo consolidation manifests.

Inputs: verification/inventory/REBOL_RED_INVENTORY.json generated by
`generate_rebol_red_inventory.py`.

Outputs are derived from inspected local inventory data only. No source files are
moved, rewritten, deleted, or normalized.
"""
from __future__ import annotations

import datetime as _dt
import json
import subprocess
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
TODAY = "2026-08-31"
TOOL = Path(__file__).relative_to(ROOT).as_posix()
INV_PATH = ROOT / "verification/inventory/REBOL_RED_INVENTORY.json"


def git(*args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()


def load_inventory() -> dict[str, Any]:
    return json.loads(INV_PATH.read_text())


def generated_header(method: str) -> dict[str, str]:
    return {
        "date": TODAY,
        "timestamp_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "tool": TOOL,
        "method": method,
        "source_inventory": INV_PATH.relative_to(ROOT).as_posix(),
        "repository_commit": git("rev-parse", "HEAD"),
        "branch": git("branch", "--show-current"),
    }


def write_json(path: str, data: dict[str, Any]) -> None:
    p = ROOT / path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def write_text(path: str, text: str) -> None:
    p = ROOT / path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)


def migration_manifest(inv: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "generated": generated_header("derive no-move migration baseline from inventory; no filesystem move operations performed"),
        "status": "NO_MOVES_PERFORMED",
        "entries": [],
        "policy": [
            "Before any future move, record old_path, new_path, classification, origin, sha256_before.",
            "After the move, calculate sha256_after and compare with sha256_before.",
            "If hashes differ, mark transformation as content-changing and investigate before claiming preservation.",
        ],
        "blocked_reason": "Physical migration requires owner decision and stronger upstream provenance for historical Red/Rebol source trees.",
        "source_inventory_commit": inv["repository"]["commit"],
    }


def duplicate_report(inv: dict[str, Any]) -> dict[str, Any]:
    files = {f["path"]: f for f in inv["files"]}
    exact = []
    for g in inv["duplicates"]["exact_sha256_groups"]:
        exact.append({
            **g,
            "classification": "IDENTICAL",
            "review_status": "PRESERVED; no deletion performed",
            "classifications_present": sorted({files[p]["classification"] for p in g["paths"] if p in files}),
        })
    filename = []
    for g in inv["duplicates"]["same_filename_groups"]:
        shas = sorted({files[p]["sha256"] for p in g["paths"] if p in files})
        relation = "IDENTICAL" if len(shas) == 1 else "RELATED-VARIANT"
        filename.append({
            **g,
            "classification": relation,
            "distinct_sha256_count": len(shas),
            "review_status": "OWNER REVIEW REQUIRED before any consolidation",
            "classifications_present": sorted({files[p]["classification"] for p in g["paths"] if p in files}),
        })
    return {
        "schema_version": 1,
        "generated": generated_header("derive duplicate groups from SHA-256, filename, and normalized-content groups in inventory"),
        "policy": "No duplicate artifacts were deleted. Same-name variants may be platform variants, generated references, fixtures, or historical variants.",
        "exact_sha256_groups": exact,
        "same_filename_groups": filename,
        "normalized_content_groups": inv["duplicates"]["normalized_content_groups"],
        "summary": {
            "exact_sha256_groups": len(exact),
            "same_filename_groups": len(filename),
            "normalized_content_groups": len(inv["duplicates"]["normalized_content_groups"]),
            "owner_review_required_groups": sum(1 for g in filename if g["classification"] != "IDENTICAL"),
        },
    }


def test_inventory(inv: dict[str, Any]) -> dict[str, Any]:
    files = inv["files"]
    test_like = []
    for f in files:
        path = f["path"]
        lower = path.lower()
        if f["classification"] == "RED-TEST" or "/tests/" in lower or lower.startswith("tests/") or lower.startswith("quick-test/") or "test" in Path(path).name.lower():
            test_like.append({
                "path": path,
                "classification": f["classification"],
                "language_hint": f.get("header_kind") or Path(path).suffix.lower() or "UNKNOWN",
                "sha256": f["sha256"],
                "discovery_status": "DISCOVERED",
                "execution_status": "NOT-RUN unless separately listed in local execution evidence",
            })
    roots = Counter()
    for t in test_like:
        p = Path(t["path"])
        roots[p.parts[0] if p.parts else t["path"]] += 1
    return {
        "schema_version": 1,
        "generated": generated_header("derive test inventory from classifications, paths, and filenames in repository inventory"),
        "summary": {
            "test_like_artifacts": len(test_like),
            "by_top_level_root": dict(sorted(roots.items())),
            "red_test_classified_files": sum(1 for t in test_like if t["classification"] == "RED-TEST"),
        },
        "artifacts": sorted(test_like, key=lambda x: x["path"]),
        "execution_summary": {
            "local_inventory_checks": "EXECUTED/PASSED; see verification/reports/LOCAL_EXECUTION_EVIDENCE.md",
            "python_pytest": "BLOCKED: pytest module unavailable",
            "red_rebol_suites": "NOT-RUN locally in this phase",
            "ci": "NOT-RUN/NOT-VERIFIED in this phase",
        },
    }


def provenance_manifest(inv: dict[str, Any]) -> dict[str, Any]:
    grouped: dict[str, dict[str, Any]] = defaultdict(lambda: {"count": 0, "paths_sample": []})
    for f in inv["files"]:
        key = f.get("upstream_project", "UNKNOWN") or "UNKNOWN"
        grouped[key]["count"] += 1
        if len(grouped[key]["paths_sample"]) < 25:
            grouped[key]["paths_sample"].append(f["path"])
    unknown_mod = sum(1 for f in inv["files"] if f.get("modification_status") == "UNKNOWN")
    return {
        "schema_version": 1,
        "generated": generated_header("summarize per-file provenance records from inventory"),
        "summary": {
            "files": len(inv["files"]),
            "upstream_project_groups": {k: v["count"] for k, v in sorted(grouped.items())},
            "unknown_modification_status_files": unknown_mod,
            "policy": "Do not upgrade provenance confidence without external evidence or reproducible comparison.",
        },
        "groups": dict(sorted(grouped.items())),
        "per_file_manifest_location": INV_PATH.relative_to(ROOT).as_posix(),
    }


def write_markdown_duplicate(data: dict[str, Any]) -> None:
    lines = [
        "# Duplicate Analysis",
        "",
        f"Generated by `{TOOL}` on {TODAY}.",
        "",
        "No duplicates were deleted or merged.",
        "",
        "## Summary",
        f"- Exact SHA-256 groups: {data['summary']['exact_sha256_groups']}",
        f"- Same filename groups: {data['summary']['same_filename_groups']}",
        f"- Normalized-content groups: {data['summary']['normalized_content_groups']}",
        f"- Owner-review-required groups: {data['summary']['owner_review_required_groups']}",
        "",
        "## Exact SHA-256 Groups",
    ]
    for g in data["exact_sha256_groups"]:
        lines.append(f"- `{g['sha256']}`: " + ", ".join(f"`{p}`" for p in g["paths"]))
    lines += ["", "## Same Filename Groups", ""]
    for g in data["same_filename_groups"][:120]:
        lines.append(f"- `{g['filename']}` ({g['classification']}, {g['distinct_sha256_count']} distinct hashes): " + ", ".join(f"`{p}`" for p in g["paths"]))
    write_text("verification/reports/DUPLICATE_ANALYSIS.md", "\n".join(lines) + "\n")


def write_markdown_tests(data: dict[str, Any]) -> None:
    lines = [
        "# Test Inventory and Status",
        "",
        f"Generated by `{TOOL}` on {TODAY}.",
        "",
        "## Summary",
        f"- Test-like artifacts discovered: {data['summary']['test_like_artifacts']}",
        f"- Files classified as RED-TEST: {data['summary']['red_test_classified_files']}",
        "",
        "## Execution Status",
    ]
    for k, v in data["execution_summary"].items():
        lines.append(f"- {k}: {v}")
    lines += ["", "## Artifacts", ""]
    for a in data["artifacts"][:200]:
        lines.append(f"- `{a['path']}` — {a['classification']} — {a['execution_status']}")
    if len(data["artifacts"]) > 200:
        lines.append(f"- ... {len(data['artifacts']) - 200} additional entries in `verification/inventory/TEST_INVENTORY.json`")
    write_text("verification/reports/TEST_STATUS.md", "\n".join(lines) + "\n")


def main() -> None:
    inv = load_inventory()
    mig = migration_manifest(inv)
    dup = duplicate_report(inv)
    tests = test_inventory(inv)
    prov = provenance_manifest(inv)
    write_json("verification/inventory/MIGRATION_MANIFEST.json", mig)
    write_json("verification/inventory/DUPLICATE_ANALYSIS.json", dup)
    write_json("verification/inventory/TEST_INVENTORY.json", tests)
    write_json("verification/provenance/PROVENANCE_MANIFEST.json", prov)
    write_markdown_duplicate(dup)
    write_markdown_tests(tests)
    print(json.dumps({
        "result": "ok",
        "outputs": [
            "verification/inventory/MIGRATION_MANIFEST.json",
            "verification/inventory/DUPLICATE_ANALYSIS.json",
            "verification/inventory/TEST_INVENTORY.json",
            "verification/provenance/PROVENANCE_MANIFEST.json",
            "verification/reports/DUPLICATE_ANALYSIS.md",
            "verification/reports/TEST_STATUS.md",
        ],
        "duplicate_summary": dup["summary"],
        "test_summary": tests["summary"],
    }, indent=2))


if __name__ == "__main__":
    main()
